cornGrowIntervalMinutes: 1
cornHarvestIntervalMinutes: 2

twilio:
  accountSid: abcd
  authToken: 1234
  phoneNumber: 5678

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout